// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210407124147_Resource_table_splitting")]
    partial class Resource_table_splitting
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnvironmentResource", b =>
                {
                    b.Property<Guid>("EnvironmentsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResourcesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EnvironmentsId", "ResourcesId");

                    b.HasIndex("ResourcesId");

                    b.ToTable("EnvironmentResources");
                });

            modelBuilder.Entity("Repository.Models.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduledStartup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduledUptime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("Repository.Models.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Name");

                    b.Property<string>("ResourceGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ResourceGroup");

                    b.HasKey("Id");

                    b.HasIndex("Name", "ResourceGroup")
                        .IsUnique();

                    b.ToTable("Resources");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Resource");
                });

            modelBuilder.Entity("Repository.Models.VirtualMachine", b =>
                {
                    b.HasBaseType("Repository.Models.Resource");

                    b.ToTable("Resources");

                    b.HasDiscriminator().HasValue("VirtualMachine");
                });

            modelBuilder.Entity("Repository.Models.VirtualMachineScaleSet", b =>
                {
                    b.HasBaseType("Repository.Models.Resource");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.ToTable("Resources");

                    b.HasDiscriminator().HasValue("VirtualMachineScaleSet");
                });

            modelBuilder.Entity("EnvironmentResource", b =>
                {
                    b.HasOne("Repository.Models.Environment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Models.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repository.Models.VirtualMachine", b =>
                {
                    b.HasOne("Repository.Models.Resource", null)
                        .WithOne("VirtualMachine")
                        .HasForeignKey("Repository.Models.VirtualMachine", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repository.Models.VirtualMachineScaleSet", b =>
                {
                    b.HasOne("Repository.Models.Resource", null)
                        .WithOne("VirtualMachineScaleSet")
                        .HasForeignKey("Repository.Models.VirtualMachineScaleSet", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repository.Models.Resource", b =>
                {
                    b.Navigation("VirtualMachine");

                    b.Navigation("VirtualMachineScaleSet");
                });
#pragma warning restore 612, 618
        }
    }
}
